[phases.setup]
nixPkgs = [
    "python3",
    "python3.pkgs.pip",
    "python3.pkgs.setuptools",
    "gcc",
    "pkg-config",
    "nodejs",
    "yarn"
]
aptPkgs = ["python3-dev", "build-essential"]

[phases.install]
cmds = [
    "python3 -m pip install --user distutils-extra",
    "yarn config set python python3",
    "yarn install"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start --schema $RAILWAY_DEPLOYMENT_ID"

[variables]
PYTHON = "python3"
PYTHONPATH = "/usr/lib/python3/dist-packages"
