[build]
builder = "nixpacks"
buildCommand = "yarn install"

[deploy]
startCommand = "yarn start --schema $RAILWAY_DEPLOYMENT_ID"
healthcheckPath = "/ready"
healthcheckTimeout = 86400
restartPolicyType = "on_failure"
